### ISSUE TITLE
Environment variable query

### ISSUE THREAD

**Issue by M4X1MUS07** [RISHAB-CREATOR/RgShowsApi#1]
I wanted to host this API by myself but I'm not sure what "baseURL" you're using. Is it possible for you to disclose the "process.env.BASE_URL!"?

**Comment by M4X1MUS07** [comment]
I've figured it out, sorry for the trouble.

**Comment by RISHAB-CREATOR** [comment]
Sorry for inconvenience and late reply 😔 
BASE_URL=https://allmovieland.link/player.js?v=60%20128
Check the Docker for reference.

Thank you
